#!/usr/bin/env python3
"""Generate the static city-hub pages and regenerate sitemap.xml.

One page per origin in pairings.CURATED_PAIRINGS, written to
<public>/<city-slug>/index.html, plus a rebuilt sitemap.xml that lists every hub
alongside the core pages. Idempotent: re-seeds + re-verifies pairings first so
heroes reflect current fares, then renders.

Usage:
    python -m scripts.generate_hubs [--db PATH] [--public DIR]

--db defaults to $DATABASE_PATH, then /var/lib/promptiv/teaser.sqlite.
--public defaults to the repo's public/ directory.
"""
import argparse
import json
import os
import sqlite3
from datetime import date, datetime, timezone
from pathlib import Path

from server import pairings, hubs, hub_render
from server.migrations import init_schema

CANONICAL_BASE = "https://promptiv.io"

# Punchy homepage display names that differ from the catalog (the hubs use the
# fuller catalog names). Applied on top of hubs.DISPLAY_NAMES by IATA.
SHORT_NAMES = {"LAS": "Vegas", "SJD": "Cabo"}

# Core pages and their sitemap hints, kept in sync with the original sitemap.
CORE_PAGES = [
    ("/", "weekly", "1.0"),
    ("/go", "weekly", "0.8"),
    ("/privacy", "yearly", "0.2"),
    ("/terms", "yearly", "0.2"),
]


def generate(db_path: str, public_dir: Path) -> list:
    init_schema(db_path)
    conn = sqlite3.connect(db_path)
    try:
        pairings.seed_pairings(conn)
        pairings.verify_all(conn, now=datetime.now(timezone.utc).isoformat())

        origins = [o for o, _, _ in pairings.CURATED_PAIRINGS]
        written = []
        for origin in origins:
            hub = hubs.build_hub(conn, origin)
            if not hub["trips"]:
                print(f"  SKIP {origin}: no trip data")
                continue
            slug = hub_render.slugify(hub["origin_city"])
            html = hub_render.render_hub(hub)
            out_dir = public_dir / slug
            out_dir.mkdir(parents=True, exist_ok=True)
            (out_dir / "index.html").write_text(html, encoding="utf-8")
            hero = "hero" if hub["hero"] else "NO HERO"
            print(f"  {origin} -> /{slug}  ({len(hub['trips'])} trips, {hero})")
            written.append(slug)
        _write_pairings_js(conn, public_dir)
    finally:
        conn.close()

    _write_sitemap(public_dir, written)
    return written


def _write_pairings_js(conn, public_dir: Path) -> None:
    """Emit public/pairings.js (window.PROMPTIV_PAIRINGS) from the VERIFIED
    pairings so the homepage rotation + geo headlines track the fact monitor and
    never show an unverified claim. app.js falls back to its built-in copy if
    this file is missing."""
    entries = []
    for origin, _, _ in pairings.CURATED_PAIRINGS:
        hl = pairings.get_headline(conn, origin, display_names=hubs.DISPLAY_NAMES)
        if not hl:
            print(f"  pairings.js: skip {origin} (unverified)")
            continue
        arow = conn.execute(
            "SELECT city, lat, lng FROM airports WHERE iata=?", (origin,)
        ).fetchone()
        if not arow:
            continue
        city, lat, lng = arow
        entries.append({
            "city": city,
            "slug": hub_render.slugify(city),
            "lat": round(lat, 3),
            "lng": round(lng, 3),
            "cheap": SHORT_NAMES.get(hl["cheap_iata"]) or hl["cheap_city"],
            "anchor": SHORT_NAMES.get(hl["anchor_iata"]) or hl["anchor_city"],
        })
    js = ("// Generated by scripts/generate_hubs.py from verified city_pairings.\n"
          "// Do not edit by hand. app.js reads window.PROMPTIV_PAIRINGS.\n"
          "window.PROMPTIV_PAIRINGS = " + json.dumps(entries, ensure_ascii=False, indent=2) + ";\n")
    (public_dir / "pairings.js").write_text(js, encoding="utf-8")
    print(f"  pairings.js: {len(entries)} verified pairings")


def _write_sitemap(public_dir: Path, hub_slugs: list) -> None:
    today = date.today().isoformat()
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by scripts/generate_hubs.py. Do not edit by hand: the hub",
        "     generator rewrites this on every run to keep all city pages listed. -->",
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for loc, changefreq, priority in CORE_PAGES:
        parts += _url(f"{CANONICAL_BASE}{loc}", today, changefreq, priority)
    for slug in hub_slugs:
        parts += _url(f"{CANONICAL_BASE}/{slug}", today, "weekly", "0.7")
    parts.append("</urlset>")
    (public_dir / "sitemap.xml").write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"  sitemap.xml: {len(CORE_PAGES)} core + {len(hub_slugs)} hubs")


def _url(loc: str, lastmod: str, changefreq: str, priority: str) -> list:
    return [
        "  <url>",
        f"    <loc>{loc}</loc>",
        f"    <lastmod>{lastmod}</lastmod>",
        f"    <changefreq>{changefreq}</changefreq>",
        f"    <priority>{priority}</priority>",
        "  </url>",
    ]


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=os.environ.get("DATABASE_PATH", "/var/lib/promptiv/teaser.sqlite"))
    ap.add_argument("--public", default=str(repo_root / "public"))
    args = ap.parse_args()
    print(f"generating hubs from {args.db} into {args.public}")
    written = generate(args.db, Path(args.public))
    print(f"done: {len(written)} hubs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
